# Tasks required to have the release-tools working for the vagrant user
- name: Release tools | Packaged dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libhtml-tableextract-perl
    - libtext-multimarkdown-perl

- name: Release tools | CPAN dependencies
  become_user: root
  cpanm:
    name: "{{ item }}"
    mirror: "{{ cpan_mirror }}"
  with_items:
    - File::FindLib
    - REST::Client

- name: Release tools | Clone repository
  git:
    repo: "{{ release_tools_repo }}"
    dest: "{{ release_tools_dir }}"
    version: "{{ release_tools_version }}"
